name: Fly Deploy
on: ["push"]

env:
    PROJECT_NAME_UNDERSCORE: privacy_redirect
    CARGO_INCREMENTAL: 0
    RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort
    RUSTDOCFLAGS: -Cpanic=abort


concurrency:
  group: fly-production
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build.sh
      - run: cargo check --all-targets
      - run: cargo clippy
      - run: cargo test

  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build.sh
      - run: cargo test
      - run: cargo test --doc

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    steps:
    - run: ./build.sh
    - name: Generate test result and coverage report
      run: |
          cargo install cargo2junit grcov rust-covfix;
          cargo test --features coverage $CARGO_OPTIONS -- -Z unstable-options --format json | cargo2junit > results.xml;
          zip -0 ccov.zip `find . \( -name "$PROJECT_NAME_UNDERSCORE*.gc*" \) -print`;
          grcov ccov.zip -s . -t lcov --llvm --branch --ignore-not-existing --ignore "/*" --ignore "tests/*" -o lcov.info;
          rust-covfix -o lcov_correct.info lcov.info;

