[package]
name = "privacy-redirect"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracking-params = {path = "../tracking-params"}

actix-web = "4.2.1"
actix-files = "0.6.2"
anyhow = "1.0.67"
thiserror = "1.0.38"
tracing = "0.1.19"
opentelemetry = { version = "0.17", features = ["rt-tokio-current-thread"] }
tracing-opentelemetry = { version = "0.18" }
tracing-subscriber = { version = "0.3", features = ["registry", "env-filter"] }
tracing-bunyan-formatter = "0.3"
tracing-actix-web = "0.7.0"
tracing-log = "0.1.1"
chrono = { version = "0.4.23", features = ["serde"]}
serde = "1.0.151"
serde_derive = "1.0.151"
serde_json = "1.0.91"
urlencoding = "2.1.2"
html-escape = "0.2.13"